### ISSUE TITLE
Validate throttle value before setting in Redis

### ISSUE THREAD

**Issue by AlecRosenbaum** [closeio/limitlion#17]
Currently, you can use [`throttle_set`](https://github.com/closeio/limitlion/blob/322b07457ed06e4a4656df53e92de520f4be5509/limitlion/throttle.py#L148) to send garbage values to Redis, which will break throttling.

Before setting in Redis,`throttle_set` should do some basic validation to make sure given values are positive floats. If the values don't look like floats, an exception should be raised (probably either a `ValueError` or a new `limitlion`-specific error).

**Comment by jkemp101** [comment]
Need to do a quick review of the Lua code to confirm `0` and floats vs. ints are ok for each setting.
